### ISSUE TITLE
x86 supported?(Question)

### ISSUE THREAD

**Issue by navono** [mustafaturan/monoton#1]
I use [bus](github.com/mustafaturan/bus) with this lib, but it seems like doesn't support x86. Any possible supported x86 or have alternative use in `bus`?

Thanks.

**Comment by mustafaturan** [comment]
Hi @navono,
I would recommend using https://github.com/sony/sonyflake with an `int` to `string` wrapper for x86 systems. 

Thanks

**Comment by mustafaturan** [comment]
I think it should be `ok` now.
