### ISSUE TITLE
Question about node ID

### ISSUE THREAD

**Issue by khash** [mustafaturan/monoton#6]
The demo app is using `1` as the node ID with a comment saying you can pick a node ID from a config server or generate one from the MAC/IP.

However, although `node` is `uint64` it returns a `MaxNodeCapacityExceededError` with values more than a certain calculated number (in my case I'm generating a 64 bit FNV-1a hash from the MAC address). Can you please clarify this limit and how you suggest generating reliable values within this boundary for `node`?

**Comment by mustafaturan** [comment]
Hi @khash ,

`uint64` won't be fitting the structure, based on the reserve on the [sequencer](https://github.com/mustafaturan/monoton#included-sequencers-and-byte-orderings) the maximum integers are defined as follows:
```
Second:      16 B =>  6 B (seconds)      + 6 B (counter) + 4 B (node)
Millisecond: 16 B =>  8 B (milliseconds) + 4 B (counter) + 4 B (node)
Nanosecond:  16 B => 11 B (nanoseconds)  + 2 B (counter) + 3 B (node)
```

You can read more details in [ADR](https://github.com/mustafaturan/monoton/blob/main/docs/adrs/byte-sizes.md)

The max node byte size and value is calculated in the `configureByteSizes` method: https://github.com/mustafaturan/monoton/blob/main/monoton.go#L225

**Comment by mustafaturan** [comment]
In case if you need `MaxNodeValue`, I can create a public accessor for the value.

**Comment by khash** [comment]
Having `MaxNodeValue` publicly available would solve the problem since I can just do a mod with that. Thank you

**Comment by mustafaturan** [comment]
The sequencer should have the method available now. You can add also introduce new sequencers too in your own code base which can increase the limits for node identifiers. 

Example to access for millisecond sequencer:
```
maxNode := sequencer.NewMillisecond().MaxNode()
```
